<a href="https://colab.research.google.com/github/divdotdev/Data-Science-And-Analytics/blob/main/Class_Questions(9_6_2026).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Today's Practise Questions...9-06-2026

In [31]:
#Question 1:

# Create a 5x5 matrix of random integers between (1-90)
# Find mean of values rows and columns wise
# Replace all even numbers with -1.
# Sort the array row and column wise
# Find row and column wise sum seperately
# Count the number of -ve's in each column

In [32]:
import numpy as np

In [33]:
# Create a 5x5 matrix of random integers between (1-90)v

matrix=np.random.randint(1,91,size=(5,5))
print(matrix)

[[90 51 46  2 40]
 [83 89 26 41 90]
 [76 30  3  8 62]
 [51 73 62 70 81]
 [20 66 10 30 61]]


In [34]:
# Replace all even numbers with -1.

even_matrix=np.where(matrix%2==0,-1,matrix)
print(even_matrix)

[[-1 51 -1 -1 -1]
 [83 89 -1 41 -1]
 [-1 -1  3 -1 -1]
 [51 73 -1 -1 81]
 [-1 -1 -1 -1 61]]


In [35]:
# Find mean of values rows and columns wise
rows=np.mean(matrix,1)
columns=np.mean(matrix,0)
print(rows)
print(columns)

[45.8 65.8 35.8 67.4 37.4]
[64.  61.8 29.4 30.2 66.8]


In [36]:
# Sort the array row and column wise
sort_rows=np.sort(matrix,1)
sort_columns=np.sort(matrix,0)
print(sort_rows)
print(sort_columns)

[[ 2 40 46 51 90]
 [26 41 83 89 90]
 [ 3  8 30 62 76]
 [51 62 70 73 81]
 [10 20 30 61 66]]
[[20 30  3  2 40]
 [51 51 10  8 61]
 [76 66 26 30 62]
 [83 73 46 41 81]
 [90 89 62 70 90]]


In [37]:
# Find row and column wise sum seperately

rows_sum=np.sum(matrix,1)
columns_sum=np.sum(matrix,0)
print(rows_sum)
print(columns_sum)

[229 329 179 337 187]
[320 309 147 151 334]


In [38]:
# Count the number of -ve's in each column

negative_cnt=np.sum(matrix<0)
print(negative_cnt)

count_col=np.sum(np.where(even_matrix<0,1,0),axis=0)
print(count_col)

0
[3 2 4 4 3]


In [39]:
# Question 2:

# Inventory Control System

# Task:

# Create a 5x5 array (stock levels)
# Create anothe 5x5 array (demand)
# Compute:
# Remaining stock = stock - demand
# Replace:
# Negative values -> 0(Out of Stock)
# Find:
# Total Storage
# Products with zero stock
# Sort each row based on remaining stock

In [40]:
import numpy as np

In [41]:
# Create a 5x5 array (stock levels)
stock=np.random.randint(20,80,size=(5,5))
print(stock)

[[74 33 30 42 22]
 [26 70 53 53 57]
 [36 53 42 79 40]
 [30 78 56 62 33]
 [75 45 26 54 35]]


In [42]:
# Create a 5x5 array (demand)
demand=np.random.randint(20,80,size=(5,5))
print(demand)


[[28 32 20 70 49]
 [39 61 20 25 43]
 [23 57 36 40 60]
 [24 68 72 70 40]
 [46 69 47 74 77]]


In [43]:
# Compute:
# Remaining stock = stock - demand

Remaining_Stock=(stock-demand)
print(Remaining_Stock)

[[ 46   1  10 -28 -27]
 [-13   9  33  28  14]
 [ 13  -4   6  39 -20]
 [  6  10 -16  -8  -7]
 [ 29 -24 -21 -20 -42]]


In [44]:
# Replace:
# Negative values -> 0(Out of Stock)

Negative_Stock=np.where(Remaining_Stock<0,0,Remaining_Stock)
print(Negative_Stock)

[[46  1 10  0  0]
 [ 0  9 33 28 14]
 [13  0  6 39  0]
 [ 6 10  0  0  0]
 [29  0  0  0  0]]


In [45]:
# Find:
# Total Shortage

Total_Shortage = np.sum(np.where(Remaining_Stock<0, Remaining_Stock * -1,0))
print(Total_Shortage)

230


In [46]:
# Products with zero stock

Product_shortage=np.sum(np.where(Remaining_Stock == 0,1,0),axis =0)
print(Product_shortage)


[0 0 0 0 0]


In [47]:
# Sort each row based on remaining stock

sorted=np.sort(Negative_Stock, axis =1)
print(sorted)

[[ 0  0  1 10 46]
 [ 0  9 14 28 33]
 [ 0  0  6 13 39]
 [ 0  0  0  6 10]
 [ 0  0  0  0 29]]
