<a href="https://colab.research.google.com/github/divdotdev/Data-Science-And-Analytics/blob/main/NUM_PY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is the need of NumPy : NumPy was needed to store data in Pyhton as an array

In [ ]:
#Importing Numpy
import numpy as np

First you have to run the upper file before running the lower one as you have to run the first file first to import numpy in the system

In [ ]:
#THIS is to create an array in numpy
a = np.array([1, 2 ,3, 4])
print(a)

[1 2 3 4]


In [ ]:
# Question
np_arr = np.array([1, 2, 3, 4])
print(bool(np_arr[-1]))

a = False
print(bool(a))

True
False


String is always a value bool only returns false when the data is empty or 0 for false, the thing in Numpy is that if it finds a string in an array of integers it converts all the elements into a string..
And in the above question the main thing is if we paas any value to a boolean type it can be anything it returns true..

In [ ]:
a = 0
print(bool(a))

b = '0'
print(bool(b))

False
True


FUNCTIONS (NumPy arrays are also known as vectors)

In [ ]:
a = np.ones((2,3,4), dtype=int)
print(a)
print(type(a[0][0][0]))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
<class 'numpy.int64'>


In [ ]:
a = np.zeros((2,3,4), dtype=int)
print(a)
print(type(a[0][0][0]))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


np.ones converts all ideas into ones
np.zeros converts all ideas into zeros

In [ ]:
c = np.empty(4, dtype=int)
print(c)

[1074436132          0          1         -1]


In [ ]:
d = np.full(4,5, dtype=int)
print(d)

[5 5 5 5]


In [ ]:
#Syntax:
# e=np.arange(start, end, jump)


e = np.arange(11,29,3, dtype=int)
print(e)

[11 14 17 20 23 26]


In [ ]:
#Syntax:
# f=np.linspace(start, end, number of values user needed)

f = np.linspace(3,12,4, dtype=int)
print(f)

[ 3  6  9 12]


Checking shape and size in 2D Arrays

In [ ]:
a=np.ones((2,3))
e=np.ones((3,4))
f=np.ones((4,2))

print(a.size)
print(e.size)
print(f.size)
print(a.shape)
print(e.shape)
print(f.shape)

6
12
8
(2, 3)
(3, 4)
(4, 2)


In [ ]:
g=np.random.randint(2,9)
print(g)

4


In [ ]:
choices=['Apple','Banana','Watermelon']
h=np.random.choice(4,7)
print(h)

[2 1 1 2 0 0 0]


In [ ]:
a = np.array((2,4,6,8))
b = np.array((10,16,12,24))
print(a*2)
print(a*b)
print(a/b)
lst=[1,2,3,4,5]
print(lst*2)

[ 4  8 12 16]
[ 20  64  72 192]
[0.2        0.25       0.5        0.33333333]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
a = np.random.randint(2,15,6)
print(a)

[ 7  3 14  3 13  2]


In [ ]:
d = a.reshape((3,2))
print(d)

[[ 7  3]
 [14  3]
 [13  2]]


In [ ]:
a = np.random.randint(0, 10, size=(3, 3))
print(a)

b = a.T
print(b)

d =np.concatenate((a, b), axis=1)
print(d)

c = np.concatenate((a, b), axis=0)
print(c)

[[7 7 1]
 [1 3 8]
 [0 4 2]]
[[7 1 0]
 [7 3 4]
 [1 8 2]]
[[7 7 1 7 1 0]
 [1 3 8 7 3 4]
 [0 4 2 1 8 2]]
[[7 7 1]
 [1 3 8]
 [0 4 2]
 [7 1 0]
 [7 3 4]
 [1 8 2]]


In [ ]:
a = np.random.randint(2,15,6)
b = np.random.randint(1,19,6)
print(a)
print(b)

c = np.where(b>2, b, a)
print(c)

[ 9  8  5  7  8 14]
[ 7  6 12  2 10  9]
[ 7  6 12  7 10  9]


In [ ]:
import numpy as np

a = np.random.randint(2, 15, 6)
b = np.random.randint(1, 19, 6)

print(a)
print(b)

c = np.where(b > 2, b, a)
print(c)

d = np.sort(a)
print(d)

e = np.sum(a)
print(e)

f = np.mean(a)
print(f)

g = np.std(a)
print(g)

h = np.min(a)
print(h)

i = np.max(a)
print(i)

j = np.unique(np.array([1, 2, 3, 2, 4, 1, 5, 3]))
print(j)

m1 = np.array([[1, 2],
               [3, 4]])

m2 = np.array([[5, 6],
               [7, 8]])

k = np.matmul(m1, m2)
print(m1)
print(m2)
print(k)

[ 2  3 11  8  9  6]
[ 9 10 17  6 11 12]
[ 9 10 17  6 11 12]
[ 2  3  6  8  9 11]
39
6.5
3.2015621187164243
2
11
[1 2 3 4 5]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [ ]:
import numpy as np

# runs = []
# days = ['mon','tue','wed','thur','fri','sat','sun']
# for i in range(7):
#     x = input(f'Enter the runs scored on {days[i]} : ')

scores=input().split()


runs = np.array(runs)

print(runs)

a = np.sum(runs)
print(a)

b = np.mean(runs)
print(b)

c = np.min(runs)
print(c)

d = np.max(runs)
print(d)

e = np.std(runs)
print(e)

KeyboardInterrupt: Interrupted by user